// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9HGAz4ps8QtZZlCTLqDQgKuQMNXWF6o',
    appId: '1:1035238060217:android:24e1dbfeadd06e37522b68',
    messagingSenderId: '1035238060217',
    projectId: 'flutter3-6c0d5',
    storageBucket: 'flutter3-6c0d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGqONAywd0rLZOOULSNfeSQqZQdN-bBjQ',
    appId: '1:1035238060217:ios:090832cb1d5779b4522b68',
    messagingSenderId: '1035238060217',
    projectId: 'flutter3-6c0d5',
    storageBucket: 'flutter3-6c0d5.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdhksTc7nqLtIsVtvfJ_dxoh3XAhVyyBU',
    appId: '1:1035238060217:web:6d672209ac48745c522b68',
    messagingSenderId: '1035238060217',
    projectId: 'flutter3-6c0d5',
    authDomain: 'flutter3-6c0d5.firebaseapp.com',
    storageBucket: 'flutter3-6c0d5.appspot.com',
    measurementId: 'G-SBMB622YDW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGqONAywd0rLZOOULSNfeSQqZQdN-bBjQ',
    appId: '1:1035238060217:ios:090832cb1d5779b4522b68',
    messagingSenderId: '1035238060217',
    projectId: 'flutter3-6c0d5',
    storageBucket: 'flutter3-6c0d5.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdhksTc7nqLtIsVtvfJ_dxoh3XAhVyyBU',
    appId: '1:1035238060217:web:b9b3e9b8f26769c2522b68',
    messagingSenderId: '1035238060217',
    projectId: 'flutter3-6c0d5',
    authDomain: 'flutter3-6c0d5.firebaseapp.com',
    storageBucket: 'flutter3-6c0d5.appspot.com',
    measurementId: 'G-7YFD4CD8WH',
  );

}